##  1. Import the Libraries

In [102]:
import numpy as np  # numerical computations
import matplotlib.pyplot as plt  # plotting
import pandas as pd  # data analysis

## 2. Import the dataset

In [103]:
dataset=pd.read_csv('Data.csv')

In [104]:
dataset.head()

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes

## 3. Create a matrix of features

In [105]:
X=dataset.iloc[:,:-1].values  # the first : represents all rows, the -1 represents exclusion of last column

In [106]:
X.shape

(10, 3)

In [107]:
y=dataset.iloc[:,3].values

In [108]:
y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

## 4. Problem of Missing Data

#### In the describe code, we see two nan 

####  We replace the missing data by the entire column's mean

In [109]:
from sklearn.preprocessing import Imputer  # imputer class helps to take care of the missing data

In [110]:
imputer=Imputer(missing_values='NaN',strategy='mean',axis=0)  # may use any strategy

In [111]:
imputer=imputer.fit(X[:,1:3])   # indexes 1 and 2 as upperbound 3 is excluded
X[:,1:3]=imputer.transform(X[:,1:3])  # replaces the missing data by the mean

In [112]:
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

## 5. Categorical Data

#### Columns 0 and 3 contain categorical data as they have a few fixed categories of text
Hence we need to encode them

In [113]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder

In [114]:
labelencoder_X=LabelEncoder()

In [115]:
labelencoder_X.fit_transform(X[:,0])  # transform

array([0, 2, 1, 2, 1, 0, 2, 0, 1, 0], dtype=int64)

In [116]:
X[:,0]=labelencoder_X.fit_transform(X[:,0])  # transform assignment to X

In [117]:
X

array([[0, 44.0, 72000.0],
       [2, 27.0, 48000.0],
       [1, 30.0, 54000.0],
       [2, 38.0, 61000.0],
       [1, 40.0, 63777.77777777778],
       [0, 35.0, 58000.0],
       [2, 38.77777777777778, 52000.0],
       [0, 48.0, 79000.0],
       [1, 50.0, 83000.0],
       [0, 37.0, 67000.0]], dtype=object)

#### But there is no relational value as assigned by the scaler as 1,2 or 0. Clearly Germany>France doesn't make any sense

#### Hence, we would use dummy encoding

In [118]:
onehotencoder=OneHotEncoder(categorical_features=[0])  # a 3-bit dummy variable assignment

In [119]:
X=onehotencoder.fit_transform(X).toarray()  # do not need to writeX[:,..] bcuz we already specified while creating the object

In [120]:
X

array([[1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 4.40000000e+01,
        7.20000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 2.70000000e+01,
        4.80000000e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 3.00000000e+01,
        5.40000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 3.80000000e+01,
        6.10000000e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 4.00000000e+01,
        6.37777778e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 3.50000000e+01,
        5.80000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 3.87777778e+01,
        5.20000000e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 4.80000000e+01,
        7.90000000e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 5.00000000e+01,
        8.30000000e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 3.70000000e+01,
        6.70000000e+04]])

In [121]:
labelencoder_y=LabelEncoder()  # Now y has only 2 categories, hence 0 and 1 would suffice.

In [122]:
labelencoder_y.fit_transform(y)

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1], dtype=int64)

In [123]:
y=labelencoder_y.fit_transform(y)

In [124]:
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1], dtype=int64)

## 6.Test set, Train Set 

#### For adapting to a new set

In [125]:
from sklearn.cross_validation import train_test_split

In [126]:
X.shape

(10, 5)

In [127]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)  # randomness is given by random set

In [128]:
X_train

array([[0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 4.00000000e+01,
        6.37777778e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 3.70000000e+01,
        6.70000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 2.70000000e+01,
        4.80000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 3.87777778e+01,
        5.20000000e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 4.80000000e+01,
        7.90000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 3.80000000e+01,
        6.10000000e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 4.40000000e+01,
        7.20000000e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 3.50000000e+01,
        5.80000000e+04]])

In [129]:
type(X_train)

numpy.ndarray

In [130]:
X_train.shape

(8, 5)

In [131]:
X_test

array([[0.0e+00, 1.0e+00, 0.0e+00, 3.0e+01, 5.4e+04],
       [0.0e+00, 1.0e+00, 0.0e+00, 5.0e+01, 8.3e+04]])

In [132]:
y_train

array([1, 1, 1, 0, 1, 0, 0, 1], dtype=int64)

In [133]:
y_test

array([0, 0], dtype=int64)

## 7. Feature Scaling

#### Is done in order to maintain the aspect of the Eucliden Distance or Covergence

#### Way one is Standardisation (x-mean)/stdDev  

#### other is normalization (x-min)/(max-min)

In [134]:
from sklearn.preprocessing import StandardScaler

In [135]:
sc_X=StandardScaler()

In [136]:
X_train=sc_X.fit_transform(X_train)   # for the training set, first we fit it and then transform it

In [137]:
X_test=sc_X.transform(X_test)

#### Do we need to scale the dummy variable??

#### It depends on the context. If we scale them, it might cause some issues too.

In [138]:
X_train

array([[-1.        ,  2.64575131, -0.77459667,  0.26306757,  0.12381479],
       [ 1.        , -0.37796447, -0.77459667, -0.25350148,  0.46175632],
       [-1.        , -0.37796447,  1.29099445, -1.97539832, -1.53093341],
       [-1.        , -0.37796447,  1.29099445,  0.05261351, -1.11141978],
       [ 1.        , -0.37796447, -0.77459667,  1.64058505,  1.7202972 ],
       [-1.        , -0.37796447,  1.29099445, -0.0813118 , -0.16751412],
       [ 1.        , -0.37796447, -0.77459667,  0.95182631,  0.98614835],
       [ 1.        , -0.37796447, -0.77459667, -0.59788085, -0.48214934]])

In [139]:
X_test

array([[-1.        ,  2.64575131, -0.77459667, -1.45882927, -0.90166297],
       [-1.        ,  2.64575131, -0.77459667,  1.98496442,  2.13981082]])

####  Here we do not need to do feature classification for y as they are already categorized as 0 or 1