# The Numpy Library in Python

In [1]:
import numpy as np

In [2]:
L=[1,2,3]

In [3]:
A=np.array(L)

In [4]:
A

array([1, 2, 3])

In [5]:
L

[1, 2, 3]

In [6]:
L.append(23)

In [7]:
L


[1, 2, 3, 23]

### can't do that with np

In [9]:
A+A # does addition (vector) not concatination

array([2, 4, 6])

In [10]:
2*A

array([2, 4, 6])

In [11]:
2*L

[1, 2, 3, 23, 1, 2, 3, 23]

In [13]:
A**2


array([1, 4, 9], dtype=int32)

In [14]:
L2=[]
for i in L:
    L2.append(i**2)
L2

[1, 4, 9, 529]

In [15]:
np.log(A)

array([0.        , 0.69314718, 1.09861229])

### Dot Product

In [16]:
a=np.array([1,2,3])

In [17]:
b=np.array([2,4,1])

In [18]:
d=0
for e,f in zip(a,b):
    d+=e*f
d

13

In [20]:
a*b # can't use it for diff sizes

array([2, 8, 3])

In [21]:
np.sum(a*b)

13

In [22]:
(a*b).sum()

13

In [23]:
np.dot(a,b)

13

In [24]:
a.dot(b)

13

In [29]:
amagA=np.sqrt((a*a).sum())
amagB=np.sqrt((b*b).sum())

In [30]:
amagA

3.7416573867739413

In [31]:
amagA=np.linalg.norm(a)
amagB=np.linalg.norm(b)

In [32]:
amagA

3.7416573867739413

In [33]:
angle=np.arccos(a.dot(b)/(amagA*amagB))

In [34]:
angle

0.7102860367200124

In [35]:
a=int(input())

23


In [36]:
a

23

In [37]:
M=np.array([[1,2,3],[3,4,5],[7,8,9]])

In [38]:
M

array([[1, 2, 3],
       [3, 4, 5],
       [7, 8, 9]])

In [39]:
M[0][0]

1

In [41]:
M[0,0]

1

In [44]:
M2=np.matrix([[1,2,3],[3,4,5],[7,8,9]]) # do not use this often, not recommended

In [45]:
M2

matrix([[1, 2, 3],
        [3, 4, 5],
        [7, 8, 9]])

In [47]:
M.T  # transpose

array([[1, 3, 7],
       [2, 4, 8],
       [3, 5, 9]])

In [48]:
Z=np.zeros(10)

In [49]:
Z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [55]:
Z2=np.zeros((10,7))

In [56]:
Z2

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [74]:
R=np.random.random((7,10))

In [75]:
R

array([[0.14763888, 0.60228482, 0.41830752, 0.91934175, 0.32011452,
        0.12344034, 0.57874195, 0.40709845, 0.61983172, 0.40487169],
       [0.99775268, 0.34193372, 0.16371788, 0.21141399, 0.26970776,
        0.44982641, 0.75224808, 0.93538981, 0.81239191, 0.39918597],
       [0.53852709, 0.72298301, 0.42882949, 0.70970559, 0.057489  ,
        0.58069259, 0.94237419, 0.3922626 , 0.40938625, 0.65983062],
       [0.75437731, 0.46021163, 0.03223963, 0.80288889, 0.97082928,
        0.65296143, 0.01170777, 0.66036494, 0.82049635, 0.17158119],
       [0.26957519, 0.09813787, 0.99896734, 0.48384196, 0.68793858,
        0.81778308, 0.4971259 , 0.31669035, 0.07044451, 0.42472484],
       [0.83371228, 0.67392279, 0.22268011, 0.73410189, 0.25998284,
        0.29367429, 0.70221919, 0.75490504, 0.97374585, 0.69982532],
       [0.83744514, 0.0600651 , 0.48232495, 0.01389717, 0.25291412,
        0.15952826, 0.01984593, 0.96533774, 0.83415991, 0.68440092]])

In [63]:
R2=np.random.randn(3,5)

In [64]:
R2

array([[-0.33122721,  1.30447652,  0.78271884, -2.52067773, -0.36248608],
       [ 1.88189931, -0.21667967,  0.28887494,  1.3607005 , -0.62004092],
       [-2.07130734,  0.30778161,  0.44648389, -0.75667449, -0.73122539]])

In [70]:
R3=np.random.randint(4,999) # 4<5 make sure 

In [73]:
R3

996

In [76]:
Z2*R

ValueError: operands could not be broadcast together with shapes (10,7) (7,10) 

In [78]:
Z2.*R

SyntaxError: invalid syntax (<ipython-input-78-bfc027e48515>, line 1)

In [84]:
A=np.random.random((6,6))
Ainv=np.linalg.inv(A)

In [85]:
A

array([[0.0143949 , 0.31108251, 0.97319415, 0.24829453, 0.34409612,
        0.53058497],
       [0.86687767, 0.30794601, 0.24640691, 0.57681985, 0.25882537,
        0.24636371],
       [0.32280478, 0.89978291, 0.18514773, 0.10706502, 0.32728287,
        0.89863272],
       [0.83567322, 0.94366421, 0.15383327, 0.13208944, 0.84165741,
        0.8815682 ],
       [0.19647319, 0.53219224, 0.82086003, 0.77907293, 0.2138227 ,
        0.28221115],
       [0.14477016, 0.35444592, 0.75274085, 0.92806505, 0.1480189 ,
        0.73155551]])

In [86]:
Ainv

array([[ 0.72671589,  2.00925646,  0.72730902, -0.86823649, -0.7774089 ,
        -0.75096549],
       [-0.65756757, -0.30701219,  1.25409672, -0.36004347,  1.76251456,
        -1.20624969],
       [ 1.51354187,  0.81173682,  0.46987615, -0.90881009,  0.04148729,
        -0.86913602],
       [-1.3471338 , -0.70292892, -1.0157853 ,  0.75289114,  0.72861689,
         1.27319706],
       [-0.4966476 , -1.8872803 , -2.67849359,  2.7409876 ,  0.53296556,
         0.77735284],
       [ 0.42690078,  0.18949799,  0.59556034, -0.22833645, -1.7749747 ,
         1.22182013]])

In [87]:
np.linalg.det(A)

-0.08966346079585714

In [88]:
np.diag(A)

array([0.0143949 , 0.30794601, 0.18514773, 0.13208944, 0.2138227 ,
       0.73155551])

In [89]:
np.diag([1,3])

array([[1, 0],
       [0, 3]])

## Outer Product

In [90]:
a=np.array([1,2])

In [91]:
b=np.array([3,4])

In [92]:
ou=np.outer(a,b)

In [93]:
ou

array([[3, 4],
       [6, 8]])

In [94]:
np.inner(a,b)

11

In [95]:
a.dot(b)

11

In [96]:
np.diag(A).sum()

1.5849562959960277

In [97]:
np.trace(A)

1.5849562959960277

In [99]:
X=np.random.randn(100,3)  # 100 samples , 3 features

In [101]:
cov=np.cov(X)

In [102]:
cov

array([[ 1.03068312,  0.75129951, -0.75344232, ...,  0.82303018,
         0.61697069,  0.35112646],
       [ 0.75129951,  0.55461896, -0.56217109, ...,  0.55739414,
         0.52270742,  0.32408056],
       [-0.75344232, -0.56217109,  0.57487461, ..., -0.52255338,
        -0.58669408, -0.38335233],
       ...,
       [ 0.82303018,  0.55739414, -0.52255338, ...,  0.91679246,
         0.04736616, -0.13535962],
       [ 0.61697069,  0.52270742, -0.58669408, ...,  0.04736616,
         1.13322861,  0.92338629],
       [ 0.35112646,  0.32408056, -0.38335233, ..., -0.13535962,
         0.92338629,  0.78547906]])

In [104]:
cov.shape

(100, 100)

In [105]:
cov=np.cov(X.T)

In [106]:
cov.shape

(3, 3)

In [107]:
np.linalg.eigh(cov)  

(array([0.65841024, 0.96210703, 1.38322572]),
 array([[-0.16569792, -0.87974658, -0.44563456],
        [ 0.925048  ,  0.01796699, -0.37942507],
        [ 0.34180461, -0.4751033 ,  0.81083072]]))

In [108]:
np.linalg.eig(cov)

(array([1.38322572, 0.96210703, 0.65841024]),
 array([[ 0.44563456,  0.87974658, -0.16569792],
        [ 0.37942507, -0.01796699,  0.925048  ],
        [-0.81083072,  0.4751033 ,  0.34180461]]))

In [109]:
A=np.array([[1,3],[4,5]])

In [110]:
A

array([[1, 3],
       [4, 5]])

In [113]:
B=np.array([5,6])

In [114]:
B

array([5, 6])

In [115]:
x=np.linalg.solve(A,B)

In [116]:
x

array([-1.,  2.])

# Word Problem

In [117]:
A=np.array([[1,1],[1.5,4]])

In [118]:
b=np.array([2200,5050])

In [119]:
np.linalg.solve(A,b)

array([1500.,  700.])